global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['localhost:9100']
  - job_name: 'process'
    static_configs:
    - targets: ['localhost:9256']
  - job_name: 'grok'
    static_configs:
    - targets: ['localhost:9144']
